### ISSUE TITLE
Error during gulp

### ISSUE THREAD

**Issue by ameykshirsagar** [Brainfock/Brainfock#10]
Hi,
I am trying to build the project as per the instructions. Here is the npm dump of the error. Kindly help me out here. Thank you

`````
C:\Users\developer\Repositories\brainfock\webpack\build.js:35
        if (buildError) throw new _gulpUtil2['default'].PluginError('webpack', buildError);
                        ^
Error: ./src/client/app/app.styl
Module build failed: ModuleBuildError: Module build failed: TypeError: C:\Users\developer\Repositories\brainfock\src\client\app\app.styl:40:1
   36|
   37|   > footer
   38|     font-size .75em
   39|     font-style italic
   40|
-------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:887:5)
    at new SourceMapper (C:\Users\developer\Repositories\brainfock\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
    at Renderer.render (C:\Users\developer\Repositories\brainfock\node_modules\stylus\lib\renderer.js:94:9)
    at C:\Users\developer\Repositories\brainfock\node_modules\stylus-loader\index.js:149:12
    at tryCatchReject (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\Scheduler.js:62:19)
    at DependenciesBlock.onModuleBuildFailed (C:\Users\developer\Repositories\brainfock\node_modules\webpack-core\lib\NormalModuleMixin.js:315:19)
    at nextLoader (C:\Users\developer\Repositories\brainfock\node_modules\webpack-core\lib\NormalModuleMixin.js:270:31)
    at C:\Users\developer\Repositories\brainfock\node_modules\webpack-core\lib\NormalModuleMixin.js:292:15
    at context.callback (C:\Users\developer\Repositories\brainfock\node_modules\webpack-core\lib\NormalModuleMixin.js:148:14)
    at C:\Users\developer\Repositories\brainfock\node_modules\stylus-loader\index.js:151:11
    at Renderer.render (C:\Users\developer\Repositories\brainfock\node_modules\stylus\lib\renderer.js:107:12)
    at C:\Users\developer\Repositories\brainfock\node_modules\stylus-loader\index.js:149:12
    at tryCatchReject (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\developer\Repositories\brainfock\node_modules\when\lib\makePromise.js:590:4)
 @ ./src/client/app/app.react.js 56:0-21

npm verb lifecycle brainfock@0.28.1~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle brainfock@0.28.1~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\developer\Repositories\brainfock\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\nodejs\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Redis\;C:\Users\developer\AppData\Local\Microsoft\WindowsApps;C:\Users\developer\AppData\Roaming\npm;C:\Users\developer\AppData\Local\Android\Sdk\tools;C:\Users\developer\AppData\Local\Android\Sdk\platform-tools;C:\Users\developer\AppData\Local\Android\Sdk\build-tools\25.0.2;C:\depot_tools;C:\Users\developer\AppData\Local\atom\bin;C:\Python27;C:\Program Files\MongoDB\Server\3.2\bin;
npm verb lifecycle brainfock@0.28.1~postinstall: CWD: C:\Users\developer\Repositories\brainfock
npm info lifecycle brainfock@0.28.1~postinstall: Failed to exec postinstall script
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm verb stack Error: brainfock@0.28.1 postinstall: `gulp build --production`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid brainfock@0.28.1
npm verb cwd C:\Users\developer\Repositories\brainfock
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! brainfock@0.28.1 postinstall: `gulp build --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brainfock@0.28.1 postinstall script 'gulp build --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brainfock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brainfock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brainfock
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\developer\Repositories\brainfock\npm-debug.log
`````

**Comment by ameykshirsagar** [comment]
Same issue on the Mac

**Comment by WilixLead** [comment]
I have same issue in Mac Sierra 10.12

```
[15:21:16] Starting 'build-webpack'...
(node:36046) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[copy-webpack-plugin] WARNING - unable to locate './src/common/app/favicons/' at '/Users/dmitry/work/brainfock/src/common/app/favicons'

/Users/dmitry/work/brainfock/webpack/build.js:36
    if (buildError) throw new _gulpUtil2.default.PluginError('webpack', buildError);
                    ^
Error: ./src/client/main.js
Module not found: Error: Can't resolve 'react-tap-event-plugin' in '/Users/dmitry/work/brainfock/src/client'
resolve 'react-tap-event-plugin' in '/Users/dmitry/work/brainfock/src/client'
  Parsed request is a module
  using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./src/client)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./src/client)
    resolve as module
      /Users/dmitry/work/brainfock/src/client/node_modules doesn't exist or is not a directory
      /Users/dmitry/work/brainfock/src/node_modules doesn't exist or is not a directory
      /Users/dmitry/work/node_modules doesn't exist or is not a directory
      /Users/dmitry/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/dmitry/work/brainfock/src
        using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./src)
          using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./src/react-tap-event-plugin)
            as directory
              /Users/dmitry/work/brainfock/src/react-tap-event-plugin doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dmitry/work/brainfock/src/react-tap-event-plugin doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dmitry/work/brainfock/src/react-tap-event-plugin.js doesn't exist
      looking for modules in /Users/dmitry/work/brainfock/node_modules
        using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./node_modules)
          using description file: /Users/dmitry/work/brainfock/package.json (relative path: ./node_modules/react-tap-event-plugin)
            as directory
              /Users/dmitry/work/brainfock/node_modules/react-tap-event-plugin doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dmitry/work/brainfock/node_modules/react-tap-event-plugin doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/dmitry/work/brainfock/node_modules/react-tap-event-plugin.js doesn't exist
```

**Comment by c3pknow** [comment]
I have same error as @ameykshirsagar.  Anyone found a resolution?

**Comment by ameykshirsagar** [comment]
@c3pknow : No solution found. Apparently as I progress the node versions. New issues come up.
Any way are we missing dependencies in terms of system libraries ??
