### ISSUE TITLE
Missing packages and files

### ISSUE THREAD

**Issue by cvramirez** [Brainfock/Brainfock#11]
This looks really awesome!

Experiencing some issues however.  I saved all the failed install logs, but you (Brainfock) may find it easier to try to do a clean install in a folder and see them for yourself.  

Firstly, the src\common\app\favicons folder was missing... added that.  (It's empty, but no more complaints)

Then the package redux-storage wasn't installed... I did that-->  "npm i redux-storage -S"

And then when finally compiled, is said  CreateBrowserHistory was missing in the source...  :(    BUT, really, it was a module import... and that module 'history' had changed a path,so it broke the code.

Remove '/lib' from line 5 of src/client/main.js: 
- bad:  import createBrowserHistory from 'history/lib/createBrowserHistory';
- fixed: import createBrowserHistory from 'history/createBrowserHistory';

It told me it was listening on localhost:3000, but when I went there, I got the following:

500 TypeError: (0 , _history.createMemoryHistory)(...).createLocation is not a function
   at render (c:/Dev/OSRepo/Brainfock/src/server/frontend/render.js:58:42)
   at Layer.handle [as handle_request] (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\layer.js:95:5)
   at next (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\route.js:137:13)
   at Route.dispatch (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\layer.js:95:5)
   at c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:281:22
   at param (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:354:14)
   at param (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:410:3)
   at next (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:275:10)
   at c:\Dev\OSRepo\Brainfock\node_modules\express-device\lib\device.js:46:26
   at Layer.handle [as handle_request] (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:317:13)
   at c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:284:7
   at Function.process_params (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:335:12)
   at next (c:\Dev\OSRepo\Brainfock\node_modules\express\lib\router\index.js:275:10)

I tried replacing (in src/server/frontend/render.js)
- this:  import {createMemoryHistory} from 'history';
- with:  import createMemoryHistory from 'history/createMemoryHistory';

But that didn't help...  I don't know what else to do.   Any ideas?

Thanks in advance!
C

**Comment by Webkadabra** [comment]
it's like you expect free thing to work lol. It was working for odler Babel and React. I tried to fix it for a newer libraries, but I failed. Nobody gives a shit, so why should I

**Comment by Webkadabra** [comment]
this was a working project for about a year. I had no help, no pull request and no donations. I guess this is now just an example repo of how opensource really sucks :( We had it all including demo server, but nobody cared until I ran out of money to support it by myself. I would never suggest going opensource these days if you're just a broke single developer

**Comment by tsanyqudsi** [comment]
@Webkadabra you need a VPS ? i think i can provide you with one. but it's a cheap VPS
