### ISSUE TITLE
Spread operator error during npm install

### ISSUE THREAD

**Issue by bcomerford** [Brainfock/Brainfock#12]
During initial build I'm receiving this error, using node 4.x and npm 3.x

> gulp build --production

[12:53:28] Requiring external module babel-register
~\brainfock\webpack\makeConfig.js:126
      }, ...stylesLoaders]
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)

**Comment by dvision1979** [comment]
2 years later I have the same issue, but there is no fix yet?
