### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by akbarbashakm** [Brainfock/Brainfock#18]
Hi,
I am trying to install the npm but it's thrown the following error.

> bufferutil@1.2.1 install A:\Component\Brainfock-master\node_modules\bufferutil
> node-gyp rebuild

A:\Component\Brainfock-master\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild
)
gyp ERR! configure error(C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\akbarkm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd A:\Component\Brainfock-master\node_modules\bufferutil
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> utf-8-validate@1.2.2 install A:\Component\Brainfock-master\node_modules\utf-8-validate
> node-gyp rebuild

A:\Component\Brainfock-master\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error(C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\akbarkm\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\akbarkm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd A:\Component\Brainfock-master\node_modules\utf-8-validate
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> brainfock@0.28.1 postinstall A:\Component\Brainfock-master
> gulp build --production

[10:21:13] Failed to load external module @babel/register
[10:21:13] Requiring external module babel-register
A:\Component\Brainfock-master\webpack\makeConfig.js:126
      }, ...stylesLoaders]
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (A:\Component\Brainfock-master\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (A:\Component\Brainfock-master\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (A:/Component/Brainfock-master/webpack/build.js:3:1)
    at Module._compile (module.js:409:26)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"}
(current: {"os":"win32","arch":"x64"})
npm WARN awesome-typescript-loader@3.5.0 requires a peer of typescript@^2 but none was installed.
npm WARN material-ui@0.17.4 requires a peer of react-tap-event-plugin@^2.0.1 but none was installed.
npm WARN react-native@0.41.2 requires a peer of react@~15.4.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\akbarkm\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! brainfock@0.28.1 postinstall: `gulp build --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brainfock@0.28.1 postinstall script 'gulp build --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brainfock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brainfock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brainfock
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     A:\Component\Brainfock-master\npm-debug.log

 Kindly help me out here. Thank you

**Comment by Webkadabra** [comment]
Guys, this application was working fully on old nodeJs version (what was it... 0.4?). I'm sorry I did not submit lock file for packages.... but if someone is willing to install old nodeJS and take time to update most packages requirements to versions that were released during the time first public code was released - then app should work fine
