### ISSUE TITLE
TypeError: Router.use() requires a middleware function but got a undefined

### ISSUE THREAD

**Issue by narendra0021** [Brainfock/Brainfock#19]
> Brainfock@0.23.0 start /home/js10/Desktop/Project/brain/Brainfock
> NODE_ENV=production node src/server

Trying to boot server...
loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. src/server/boot/cookie-auth.js:11:20
  if (err) throw err;
           ^

TypeError: Router.use() requires a middleware function but got a undefined
    at Function.use (/home/js10/Desktop/Project/brain/Brainfock/node_modules/express/lib/router/index.js:458:13)
    at Function.useAndSort [as use] (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback/lib/server-app.js:261:36)
    at EventEmitter.<anonymous> (/home/js10/Desktop/Project/brain/Brainfock/node_modules/express/lib/application.js:220:21)
    at Array.forEach (native)
    at EventEmitter.use (/home/js10/Desktop/Project/brain/Brainfock/node_modules/express/lib/application.js:217:7)
    at Object.mountLoopBackExplorer [as func] (/home/js10/Desktop/Project/brain/Brainfock/src/server/boot/explorer.js:19:10)
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:316:22
    at iterate (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:321:9
    at iterate (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:321:9
    at iterate (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:162:9)
    at runScripts (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:306:9)
    at runBootScripts (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:450:3)
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/lib/executor.js:48:7
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:607:21
    at /home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:246:17
    at iterate (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/home/js10/Desktop/Project/brain/Brainfock/node_modules/loopback-boot/node_modules/async/lib/async.js:162:9)

npm ERR! Linux 3.13.0-106-generic
npm ERR! argv "/home/js10/.nvm/versions/node/v5.6.0/bin/node" "/home/js10/.nvm/versions/node/v5.6.0/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! Brainfock@0.23.0 start: `NODE_ENV=production node src/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Brainfock@0.23.0 start script 'NODE_ENV=production node src/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Brainfock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node src/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Brainfock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Brainfock
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/js10/Desktop/Project/brain/Brainfock/npm-debug.log

**Comment by Webkadabra** [comment]
Dude, this project was written for node 0.4

**Comment by narendra0021** [comment]
I am closing this, got the solution

**Comment by Webkadabra** [comment]
@narendra0021 anything wee can use? Please, make a pull request

**Comment by narendra0021** [comment]
@Webkadabra , right now I am not working on this project,

**Comment by narendra0021** [comment]
@Webkadabra , i was getting this error so i stop working on this project
 Error: ER_NO_SUCH_TABLE: Table 'brainfock_node.ACL' doesn't exist
if you have idea let me know, in advance thank you
