### ISSUE TITLE
The (babel-plugin-react-transform) Babel 5 plugin is being run with Babel 6

### ISSUE THREAD

**Issue by ameykshirsagar** [Brainfock/Brainfock#5]
Hi,
I am not able to install the module properly. It is getting crashed at `gulp build --production`
Here is the portion of the log

```
> brainfock@0.28.1 postinstall /Users/ameykshirsagar/Repositories/brainfock
> gulp build --production

[20:10:12] Requiring external module babel-register
/Users/ameykshirsagar/node_modules/babel-core/lib/api/node.js:98
  throw new Error("The (" + alias + ") Babel 5 plugin is being run with Babel 6.");
  ^

Error: The (babel-plugin-react-transform) Babel 5 plugin is being run with Babel 6.
    at new Plugin (/Users/ameykshirsagar/node_modules/babel-core/lib/api/node.js:98:9)
    at exports.default (/Users/ameykshirsagar/Repositories/brainfock/node_modules/babel-plugin-react-transform/lib/index.js:258:10)
    at Function.memoisePluginContainer (/Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:13)
    at Function.normalisePlugin (/Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:141:32)
    at /Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/ameykshirsagar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at compile (/Users/ameykshirsagar/node_modules/babel-register/lib/node.js:103:45)

npm verb lifecycle brainfock@0.28.1~postinstall: unsafe-perm in lifecycle true
```

**Comment by Webkadabra** [comment]
@ameykshirsagar I think this is because you have babel 6.x installed globally, and code at it's current state is for babel 5.x. Pull requests are very much welcome!

**Comment by gridworkz** [comment]
Hi: Are there any plans to move to Babel 6? If it's a small job I can tackle it with some pointers. I'm relatively new to the React world. Dave-o

**Comment by Webkadabra** [comment]
@gridworkz I haven't really worked with Babel 6 yet, but if somebody will make a pull request, semms like it would be a nice thing to have. 
During implementation, I'd check to make sure we still have server-side rendering (see wiki module, for example), admin pages are loading etc. 
I'd love to work on some of it but donations haven't really picked up (I got total about $2 donations via automated support at Gratipay haha). Please, make a pull request, I'd love our project to stay relative!

**Comment by Webkadabra** [comment]
this has been fixed by https://github.com/Brainfock/Brainfock/commit/4ae146c1454c208a01c90d75fc31fd130c9861bf
